import { GoogleGenAI } from "@google/genai";
import type { GenerationRequest, GenerationResult } from "@/lib/types";
import { resolveModelRoute } from "@/lib/model-router";

const apiKey = process.env.GEMINI_API_KEY;

const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

function cleanJsonResponse(text: string) {
  return text
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();
}

function getGeminiModel(routeModel: string) {
  // If model-router still has old OpenAI model names, safely fallback to Gemini.
  if (!routeModel || routeModel.startsWith("gpt")) {
    return process.env.GEMINI_MODEL || "gemini-1.5-flash";
  }

  return routeModel;
}

function mockResult(input: GenerationRequest): GenerationResult {
  return {
    title: `${input.template} Draft`,
    summary: "Generated in mock mode because GEMINI_API_KEY is not configured.",
    output: `Template: ${input.template}
Mode: ${input.mode}

${input.redactedPrompt}

This is a mock response. Add GEMINI_API_KEY for live generation.`,
    tags: ["mock", input.template.toLowerCase(), input.mode],
    suggestedNextAction: "Refine this draft with examples from your own experience.",
    followUpCard: {
      cardType: "next-action",
      title: "Improve with personal details",
      description: "Add one real example to make the output more authentic.",
      suggestedAction: "Add a personal example",
    },
  };
}

export async function generateThinkFastOutput(
  input: GenerationRequest
): Promise<GenerationResult> {
  if (!ai) {
    return mockResult(input);
  }

  try {
    const route = resolveModelRoute(input.mode);
    const ideaNotes = (input.ideaAnswers ?? []).join("; ");
    const model = getGeminiModel(route.model);

    const prompt = `
You are ThinkFast, a privacy-aware productivity assistant.

${route.systemStyle}

Return strict JSON only. Do not use markdown. Do not wrap the JSON in triple backticks.

The JSON must have these keys:
{
  "title": "",
  "summary": "",
  "output": "",
  "tags": [],
  "suggestedNextAction": "",
  "followUpCard": {
    "cardType": "",
    "title": "",
    "description": "",
    "suggestedAction": ""
  }
}

User request details:
Template: ${input.template}
Mode: ${input.mode}
Preferred Tone: ${input.preferredTone ?? "balanced"}
Redacted Prompt: ${input.redactedPrompt}
Idea Answers: ${ideaNotes || "None provided"}

Generate the final ThinkFast output now.
`;

    const response = await ai.models.generateContent({
      model,
      contents: prompt,
    });

    const text = response.text || "{}";
    const cleaned = cleanJsonResponse(text);

    try {
      return JSON.parse(cleaned) as GenerationResult;
    } catch {
      return {
        title: `${input.template} Output`,
        summary: "Output generated by Gemini, but structured parsing failed.",
        output: text,
        tags: [input.template.toLowerCase(), input.mode],
        suggestedNextAction: "Create a cleaner version from this draft.",
        followUpCard: {
          cardType: "follow-up",
          title: "Polish this output",
          description: "Turn this draft into a finalized format.",
          suggestedAction: "Refine output",
        },
      };
    }
  } catch (error) {
    console.error("Gemini generation error:", error);
    return mockResult(input);
  }
}