import { GoogleGenAI } from "@google/genai";
import type { GenerationRequest, GenerationResult } from "@/lib/types";
import { resolveModelRoute } from "@/lib/model-router";

function cleanJsonResponse(text: string) {
  return text.replace(/```json/g, "").replace(/```/g, "").trim();
}

function getGeminiModel(routeModel: string) {
  if (!routeModel || routeModel.startsWith("gpt")) {
    return process.env.GEMINI_MODEL || "gemini-3.1-flash-lite";
  }

  return routeModel;
}

function getFallbackReason(error?: unknown) {
  if (!process.env.GEMINI_API_KEY) {
    return {
      summary:
        "Generated in mock mode because GEMINI_API_KEY is not configured.",
      outputMessage:
        "This is a mock response. Add GEMINI_API_KEY for live generation.",
      tag: "missing-key",
    };
  }

  const message = error instanceof Error ? error.message : String(error ?? "");

  if (
    message.includes("429") ||
    message.toLowerCase().includes("quota") ||
    message.toLowerCase().includes("rate") ||
    message.toLowerCase().includes("resource_exhausted")
  ) {
    return {
      summary:
        "Generated in mock mode because Gemini rate limit or quota was reached.",
      outputMessage:
        "Gemini appears to be rate-limited or out of quota right now. ThinkFast is using mock mode so the flow can continue.",
      tag: "rate-limited",
    };
  }

  return {
    summary: "Generated in mock mode because Gemini was temporarily unavailable.",
    outputMessage:
      "Gemini failed temporarily. ThinkFast is using mock mode so the flow can continue. Try generating again in a moment.",
    tag: "gemini-unavailable",
  };
}

function mockResult(
  input: GenerationRequest,
  error?: unknown
): GenerationResult {
  const ideaNotes = (input.ideaAnswers ?? []).join("; ");
  const historyNote = input.conversationHistory?.length
    ? `\n\nPrevious conversation included ${input.conversationHistory.length} message(s).`
    : "";

  const fallback = getFallbackReason(error);

  return {
    title: `${input.template} Draft`,
    summary: fallback.summary,
    output: `Template: ${input.template}
Mode: ${input.mode}

${input.redactedPrompt}

Idea direction: ${ideaNotes || "None provided"}${historyNote}

${fallback.outputMessage}`,
    tags: [fallback.tag, input.template.toLowerCase(), input.mode],
    suggestedNextAction:
      "Try generating again, or refine this draft manually for now.",
    followUpCard: {
      cardType: "next-action",
      title: "Continue anyway",
      description:
        "You can keep editing or retry live generation when Gemini is available.",
      suggestedAction: "Retry or refine",
    },
  };
}

function formatHistory(input: GenerationRequest) {
  const history = input.conversationHistory ?? [];

  if (!history.length) {
    return "No previous conversation yet.";
  }

  return history
    .slice(-8)
    .map((item) => {
      const speaker = item.role === "user" ? "User" : "ThinkFast";
      return `${speaker}: ${item.content}`;
    })
    .join("\n\n");
}

function fallbackFromText(input: GenerationRequest, text: string): GenerationResult {
  return {
    title: `${input.template} Output`,
    summary: "Output generated by Gemini, but structured parsing failed.",
    output: text,
    tags: [input.template.toLowerCase(), input.mode],
    suggestedNextAction: "Create a cleaner version from this draft.",
    followUpCard: {
      cardType: "follow-up",
      title: "Polish this output",
      description: "Turn this draft into a finalized format.",
      suggestedAction: "Refine output",
    },
  };
}

async function generateWithModelFallbacks(
  ai: GoogleGenAI,
  modelsToTry: string[],
  prompt: string
) {
  let lastError: unknown = null;

  for (const model of modelsToTry) {
    try {
      const response = await ai.models.generateContent({
        model,
        contents: prompt,
      });

      return {
        modelUsed: model,
        text: response.text || "{}",
      };
    } catch (error) {
      lastError = error;
      console.warn(`Gemini model failed: ${model}`, error);
    }
  }

  throw lastError;
}

export async function generateThinkFastOutput(
  input: GenerationRequest
): Promise<GenerationResult> {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return mockResult(input);
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const route = resolveModelRoute(input.mode);
    const ideaNotes = (input.ideaAnswers ?? []).join("; ");

    const primaryModel = getGeminiModel(route.model);
    const fallbackModels = (route.fallbackModels ?? []).map(getGeminiModel);

    const modelsToTry = Array.from(
      new Set([primaryModel, ...fallbackModels])
    );

    const prompt = `
You are ThinkFast, an idea-first and privacy-aware AI productivity assistant.

${route.systemStyle}

Core behavior:
- Continue the user's current conversation when prior messages are provided.
- If the user answered an idea prompt, treat that answer as the user's chosen direction.
- Do not ignore the user's original request. Combine the original task with their selected or typed idea.
- The user's idea comes first, then privacy protection.
- Use the redacted prompt for generation unless the user explicitly chose to continue anyway.
- Be clear, helpful, natural, and not generic.
- Do not mention that you are returning JSON.

Return strict JSON only. Do not use markdown. Do not wrap the JSON in triple backticks.

The JSON must have these keys:
{
  "title": "",
  "summary": "",
  "output": "",
  "tags": [],
  "suggestedNextAction": "",
  "followUpCard": {
    "cardType": "",
    "title": "",
    "description": "",
    "suggestedAction": ""
  }
}

Conversation so far:
${formatHistory(input)}

Current request details:
Template: ${input.template}
Mode: ${input.mode}
Preferred Tone: ${input.preferredTone ?? "balanced"}
Original Prompt: ${input.prompt}
Redacted Prompt Used for Safety: ${input.redactedPrompt}
User's Idea Direction: ${ideaNotes || "None provided"}

Generate the next ThinkFast response now.
`;

    const { text, modelUsed } = await generateWithModelFallbacks(
      ai,
      modelsToTry,
      prompt
    );

    const cleaned = cleanJsonResponse(text);

    try {
      const parsed = JSON.parse(cleaned) as GenerationResult;

      return {
        ...parsed,
        summary: parsed.summary
          ? `${parsed.summary} Generated with ${modelUsed}.`
          : `Generated with ${modelUsed}.`,
        tags: Array.from(
          new Set([...(parsed.tags ?? []), input.template.toLowerCase(), input.mode])
        ),
      };
    } catch {
      return fallbackFromText(input, text);
    }
  } catch (error) {
    console.error("Gemini generation error:", error);
    return mockResult(input, error);
  }
}